# IMPORTANT: After editing this file, run `pnpm cf:typegen` to regenerate the
# types for the Cloudflare Workers runtime.

main = "dist/index.js"
name = "bluesky-backup-durable-objects"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[durable_objects.bindings]]
name = "BACKUP_DO"
class_name = "BackupDO"

[[migrations]]
tag = "v1"                        # Should be unique for each entry
new_sqlite_classes = ["BackupDO"] # Array of new classes


# Matches the bindings in the main worker

[[kv_namespaces]]
binding = "BLUESKY_AUTH_SESSION_STORE"
id = "0ba166be0635430ba3dfd9ba5fa2ac14"

[[kv_namespaces]]
binding = "BLUESKY_AUTH_STATE_STORE"
id = "260c99a20b724842bd9e0b69c6a57747"
