name: env-setup
description: 'Set up .env file'

runs:
  using: 'composite'
  steps:
    - name: create .env from .env.tpl
      shell: bash
      run: |
        cp .env.tpl .env
        echo "NEXT_PUBLIC_SERVER_DID='did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi'" >> .env
        echo "SERVER_IDENTITY_PRIVATE_KEY=MgCZT5vOnYZoVAeyjnzuJIVY9J4LNtJ+f8Js0cTPuKUpFne0BVEDJjEu6quFIU8yp91/TY/+MYK8GvlKoTDnqOCovCVM=" >> .env
        echo 'TOKEN_ENDPOINT_PRIVATE_KEY_JWK={"kty":"EC","kid":"b526be6c-27b5-45b6-8a86-b0592e41c643","use":"sig","crv":"P-256","x":"ZpftIy0xQZ3UcU6fuTrbJRJBeFjooCKj9oy5_uQgR8c","y":"1TtvyfJAo4k13UnnSs0fpyGmm6ZwOwVe5jfDlMUckYQ","d":"YLnxwUOClIE9L6DB8jM8alsbHN1vyJREnBj-0mMd0so"}' >> .env
