name: 'Chromatic'

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - uses: ./.github/actions/pnpm
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Always accept changes once they've merged to main, to keep baselines
          # up to date.
          autoAcceptChanges: main
          buildScriptName: 'storybook:build'
